name: Deploy to Firebase Hosting on merge

on:
    push:
        branches:
            - master

jobs:
    build_and_preview:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout branch
              uses: actions/checkout@v2

            - name: Retrieve npm cache (if any)
              uses: actions/cache@v2.1.6
              with:
                  path: ~/.npm
                  key: npm-packages

            - name: Install Dependencies
              run: npm install

            - name: Build files
              run: npm run build

            - name: Deploy Site
              uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: '${{ secrets.GITHUB_TOKEN }}'
                  firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_SITE_DD3A7 }}'
                  channelId: live
                  projectId: portfolio-site-dd3a7
